### ISSUE TITLE
Could consider using a dictionary for image list

### ISSUE THREAD

**Issue by MikeSusutZZ** [COMP2522/project-rocketman#101]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/GameManager.java#L116

Calling image[0] is confusing, calling image[bad_guy} is more clear

**Comment by Lijuan-Z** [comment]
added
