### ISSUE TITLE
commented out code

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-rocketman#102]
unclear as to which code is the correct method to find the collisions, remove the commented out code if it is not needed and explain better using comments 
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Coin.java#L100-L114

**Comment by Lijuan-Z** [comment]
deleted commented code
