### ISSUE TITLE
google checks complaints in coin class

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-rocketman#103]
the whole file flags a large amount of google checks errors, ensure you put javadocs to explain code
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Coin.java#L1-L141

**Comment by Lijuan-Z** [comment]
fixed
