### ISSUE TITLE
Unused and empty methods

### ISSUE THREAD

**Issue by gathrean** [COMP2522/project-rocketman#106]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L31

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L35

**Comment by Lijuan-Z** [comment]
deleted
