### ISSUE TITLE
A lot of unused Override methods

### ISSUE THREAD

**Issue by gathrean** [COMP2522/project-rocketman#109]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L54

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L59

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L64

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L69

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L75

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L80

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Rocket.java#L88

**Comment by Lijuan-Z** [comment]
It is used in manager and test classes.
