### ISSUE TITLE
incomplete class database.java

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-rocketman#111]
doesn't seem like this class is completed and reflects what it should be doing for the game. classes on main branch should not be this incomplete.
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Database.java#LL29C3-L33C4

**Comment by Lijuan-Z** [comment]
database implemented
