### ISSUE TITLE
Consider using OS or Path libraries to manage filenames

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-rocketman#112]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/GameManager.java#L82

https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html

https://stackoverflow.com/questions/3660824/in-java-what-are-the-packages-containing-operating-system-level-commands

**Comment by Lijuan-Z** [comment]
keep using the loadImage method
