### ISSUE TITLE
confusing return statement in buttun.java

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-rocketman#115]
consider breaking down this large if statement, it looks confusing/hard to understand at first
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Button.java#L60-L64

**Comment by Lijuan-Z** [comment]
made it clear
