### ISSUE TITLE
possible null exception button.java

### ISSUE THREAD

**Issue by shawnbirring** [COMP2522/project-rocketman#117]
getting a window object like this has a high change of being null because in window.java the getInstance is just returning window and not checking if it is null before returning it. if this goes unchecked there is a high change to find hard to track where nullpoionterexceptions is coming from
i would recommend to pass the window object to every class so that every class knows where to draw to

https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Button.java#L40

**Comment by Lijuan-Z** [comment]
passed when needed
