### ISSUE TITLE
Player feels a bit slow moving upward

### ISSUE THREAD

**Issue by MatoCode** [COMP2522/project-rocketman#146]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Player.java#L110

The player currently feels slower moving up then down, maybe try setting the max upwards speed to the same as the downward speed

**Comment by Lijuan-Z** [comment]
changed
