### ISSUE TITLE
Add Drawable interface

### ISSUE THREAD

**Issue by MatoCode** [COMP2522/project-rocketman#169]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Heart.java#L75

Both Coin and heart possess a draw method, try adding a drawable interface so you can iterate over both of them at once

**Comment by immangat** [comment]
Our Sprite class has drawable method which coins extends.
