### ISSUE TITLE
methods have no functions or unproper features.

### ISSUE THREAD

**Issue by hh001207** [COMP2522/project-rocketman#170]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Coin.java#L1

methods are either empty or just return 0. Modify the methods or delete them so that it is being properly used.

**Comment by Lijuan-Z** [comment]
deleted
