### ISSUE TITLE
Similar variables

### ISSUE THREAD

**Issue by RavdeepAulakh** [COMP2522/project-rocketman#171]
The hearts and lives variables from the name at least seem to be doing the same or similar thing if that is the case then one can be removed if that is not the case one should be named more distinctly. 
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Player.java#L37
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/Player.java#L39

**Comment by Lijuan-Z** [comment]
deleted lives
