### ISSUE TITLE
Could add unique manager for each sprite type

### ISSUE THREAD

**Issue by MikeSusutZZ** [COMP2522/project-rocketman#96]
https://github.com/COMP2522/project-rocketman/blob/769a4c03487af4b3c2d69c7ccd70685fdc67dd17/src/main/java/org/comp2522/ProjectRocketMan/GameManager.java#L220

Instead of having all of your sprites managed in game manager, you could have the code divided among different classes

**Comment by Lijuan-Z** [comment]
We preferred they are managed in the game manager class for logical reasons.
